/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline */
export type Borders = {
	fpsfaBorderRadiusSm: string;
	fpsfaBorderRadiusLg: string;
	fpsfaBorderRadiusXl: string;
	fpsfaBorderRadiusMultiValue: string
}