/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline */
export type Spacings = {
	fpsfaDimensionScale: string;
	fpsfaDimensionXs: string;
	fpsfaDimensionSm: string;
	fpsfaDimensionMd: string;
	fpsfaDimensionLg: string;
	fpsfaDimensionXl: string;
	fpsfaSpacingXs: string;
	fpsfaSpacingSm: string;
	fpsfaSpacingMd: string;
	fpsfaSpacingLg: string;
	fpsfaSpacingXl: string;
	fpsfaSpacingMultiValue: string;
	fpsfaParagraphIndent0: string
}