/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline*/
export type Theme = {
	fpsfaThemeBgDefault: string;
	fpsfaThemeBgSubtle: string;
	fpsfaThemeBgMuted: string;
	fpsfaThemeFgDefault: string;
	fpsfaThemeFgOnAccent: string;
	fpsfaThemeFgMuted: string;
	fpsfaThemeFgSubtle: string;
	fpsfaThemeAccentDefault: string;
	fpsfaThemeAccentSubtle: string;
	fpsfaColorsBlack: string;
	fpsfaColorsWhite: string;
	fpsfaColorsRed50: string;
	fpsfaColorsRed100: string;
	fpsfaColorsRed200: string;
	fpsfaColorsRed300: string;
	fpsfaColorsRed400: string;
	fpsfaColorsRed500: string;
	fpsfaColorsRed600: string;
	fpsfaColorsRed700: string;
	fpsfaColorsRed800: string;
	fpsfaColorsRed900: string;
	fpsfaColorsRed950: string;
	fpsfaColorsBlue50: string;
	fpsfaColorsBlue100: string;
	fpsfaColorsBlue200: string;
	fpsfaColorsBlue300: string;
	fpsfaColorsBlue400: string;
	fpsfaColorsBlue500: string;
	fpsfaColorsBlue600: string;
	fpsfaColorsBlue700: string;
	fpsfaColorsBlue800: string;
	fpsfaColorsBlue900: string;
	fpsfaColorsBlue950: string;
	fpsfaColorsGrey50: string;
	fpsfaColorsGrey100: string;
	fpsfaColorsGrey200: string;
	fpsfaColorsGrey300: string;
	fpsfaColorsGrey400: string;
	fpsfaColorsGrey500: string;
	fpsfaColorsGrey600: string;
	fpsfaColorsGrey700: string;
	fpsfaColorsGrey800: string;
	fpsfaColorsGrey900: string;
	fpsfaColorsGrey950: string
}