/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline*/
import { Borders } from "../types/borders.type";

export const borders: Borders = {
	fpsfaBorderRadiusSm: "4px",
	fpsfaBorderRadiusLg: "8px",
	fpsfaBorderRadiusXl: "16px",
	fpsfaBorderRadiusMultiValue: "4 8"
}