/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline*/
import { Borders } from "../types/borders.type";

export const borders: Borders = {
	fpsfaBorderRadiusSm: "4",
	fpsfaBorderRadiusLg: "8",
	fpsfaBorderRadiusXl: "16",
	fpsfaBorderRadiusMultiValue: "4 8"
}