/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline*/
import { Spacings } from "../types/spacings.type";

export const spacings: Spacings = {
	fpsfaDimensionScale: "2",
	fpsfaDimensionXs: "4",
	fpsfaDimensionSm: "8",
	fpsfaDimensionMd: "16",
	fpsfaDimensionLg: "32",
	fpsfaDimensionXl: "64",
	fpsfaSpacingXs: "4px",
	fpsfaSpacingSm: "8px",
	fpsfaSpacingMd: "16px",
	fpsfaSpacingLg: "32px",
	fpsfaSpacingXl: "64px",
	fpsfaSpacingMultiValue: "8 64",
	fpsfaParagraphIndent0: "0px"
}